apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-jc-san
spec:
  version: 1 # si
  backendName: ontap-san_192_168_205_203 # si 
  storageDriverName: ontap-san # si
  useREST: true # si
  name: backend-jc-san
  managementLIF: 192.168.204.203 # si 
  dataLIF: 192.168.205.203 # si
  svm: SVM # si 
  storagePrefix: trident # si
  useCHAP: false # si
  # chapInitiatorSecret: '' si 
  # chapTargetInitiatorSecret: '' si
  # chapUserName: '' si
  # chapTargetUsername: '' si
  # labels: '' si
  # clientCertificate: '' si
  # clientPrivateKey: '' si
  # trustedCACertificate: ' si'
  # aggregate: '' si
  # limitAggregateUsage: ''
  # limitVolumeSize: '' si
  lunsPerFlexvol: '100' # si
  sanType: iscsi # si
  # formatOptions: '' si
  # limitVolumePoolSize: '' si
  denyNewVolumePools: 'false' # si
  defaults:
    spaceReserve: none # si
    spaceAllocation: 'true' # si
    snapshotPolicy: none # si
    snapshotReserve: '0' # si
    encryption: 'false' # si
    # qosPolicy: '' # si
    # adaptiveQosPolicy: '' # si
    tieringPolicy: none
    # luksEncryption: ''
    # nameTemplate: ''
  debugTraceFlags: # si
    api: false
    method: false
  credentials: # si
    name: trident-creds

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rhoso-san
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
    argocd.argoproj.io/sync-wave: '5'
provisioner: csi.trident.netapp.io
reclaimPolicy: Delete
parameters:
  backendType: ontap-san
  fsType: ext4
  provisioningType: thin
  snapshots: 'true'
allowVolumeExpansion: true
volumeBindingMode: Immediate
