apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-ontap
  namespace: trident
spec:
  version: 1
  backendName: backend-san
  storageDriverName: ontap-san
  useREST: true
  managementLIF: sansvm-mgmt.demo.netapp.com
  dataLIF: 192.168.0.136
  svm: svm_iscsi
  storagePrefix: lab
  labels:
    backend: us-east1
    environment: test
  aggregate: aggr1
  limitAggregateUsage: '80'
  limitVolumeSize: 500Gi
  lunsPerFlexvol: '100'
  sanType: iscsi
  # formatOptions: ''
  # limitVolumePoolSize: ''
  denyNewVolumePools: 'false'
  defaults:
    spaceReserve: none
    spaceAllocation: 'true'
    snapshotPolicy: default
    snapshotReserve: none
    encryption: 'false'
    # qosPolicy: ''
    # adaptiveQosPolicy: ''
    tieringPolicy: none
    # luksEncryption: ''cat
    # nameTemplate: ''
  debugTraceFlags:
    api: false
    method: false
  credentials:
    name: trident-creds

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ontap-san-lab
  annotations:
    storageclass.kubernetes.io/is-default-class: 'false'
    argocd.argoproj.io/sync-wave: '5'
provisioner: csi.trident.netapp.io
reclaimPolicy: Delete
parameters:
  backendType: ontap-san
  fsType: ext4
  provisioningType: thin
  snapshots: 'true'
allowVolumeExpansion: true
volumeBindingMode: Immediate
