apiVersion: v1
kind: Secret
metadata:
  name: trident-creds
type: Opaque
stringData:
  username: vsadmin 
  password: Netapp1!
  chapInitiatorSecret: cl9qxWfnUFoinvk
  chapTargetInitiatorSecret: rwbwtuigONgbw
  chapUsername: uh2a1io325bFFILn
  chapTargetUsername: iJF4sgjrnwOwQ
